# Generated by Django 2.1.1 on 2018-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_identity_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='signature',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
